### ISSUE TITLE
Shutter Stops Before Being Fully Open/Closed

### ISSUE THREAD

**Issue by GeneralT001** [nexdome/ASCOM#24] opened 2020-03-20 00:33 UTC
The previous night the shutter just stopped when it was about 1/2 way open. Had to cycle the on/off switch in order to be able to manually finish opening it(before cycling the on/off switch - the toggle switch would not work after the opening error). It did the same thing on the way down.

Last night it opened fine but then - when closing it - it again stopped - but this time the toggle switch was active and I could continue to close it manually - but it would only move about 6" then stop and I would have to release the toggle and press it again before it would go another 6". I then cycled the power switch and was able to finish closing it with the manual toggle switch without issue.

Attached is the Log from last night.
[TA.Nexdome.Server-2020-03-18-DESKTOP-ORDCE65_Anthony-DESKTOP-ORDCE65.log](https://github.com/nexdome/ASCOM/files/4357442/TA.Nexdome.Server-2020-03-18-DESKTOP-ORDCE65_Anthony-DESKTOP-ORDCE65.log)

**Comment by dscbiggs** [comment] 2020-04-14 17:14
I experienced almost identical behavior.

**Comment by NameOfTheDragon** [comment] 2020-04-16 15:44
This is a problem that I have never been able to reproduce on the test bench, so it's difficult to know why it is happening. The main difference between my test setup and a real installation is that my shutter is powered by a mains PSU rather than a battery. This has led me to speculate that perhaps the shutter is suffering from power supply issues. @rpinaeu may wish to comment on that.

Your log file contains just short of 320,000 lines. It's going to be hard for me to find anything in that amount of log output unless you can narrow down the time that the issue occurred to within a few seconds. It would really help if next time it happens, you immediately write down the time and then supply _that_ log file along with the time stamp. If you can do that for me, I'll do my best to figure out what the problem is.

**Comment by GeneralT001** [comment] 2020-04-16 16:13
Hi Tim,

 

I’ve noticed that this only happens when using Voyager. I’ve addressed this with Leo (Voyager) but he is adamant that it is something on your end and not his.

 

I can reproduce this because it only seems to happen (to me at least ) when I open the open (in Voyager) without the dome being slaved. If I open the shutter (in Voyager) with the dome slaved then it opens normally. I’ll make a video to show you both instances. 

 

I haven’t had the issue in the ASCOM device hub – as far as I can recall.

 

 

Tony

**Comment by markm75** [comment] 2020-04-16 16:28
Mine does this, but via ascom device hub, very random.  When you go outside to fix it, pressing the button doesnt do anything until the power is cycled (shutter)

**Comment by GeneralT001** [comment] 2020-04-16 18:40
Hi Tim,

 

I ran that error again and here is the part of the Logs that show the error…but does it say anything other than that?

 

Time of the error is 11:28:11

 

Nexdome Log:



 

Voyager Log:

**Comment by dave4roma** [comment] 2020-05-10 16:02
I had not had this happen to me but just a couple nights ago it started.  I’ve had to go up and press the button to finish closing. It just stops halfway or even a couple inches during a close or an open.

I took off the cover and the motor board (the black one) has a red and green led at the top and they are both lit. Looks like the side of the motor board says those are for alarm and power.

My battery reads 12V so I don’t think it’s low voltage.

In TheSkyX it gives error #206 

Help!

**Comment by GeneralT001** [comment] 2020-05-10 16:18
I still think its to do with the magnets not correctly reporting that the shutter is "closed" or "open". Maybe you closed the shutter when the magnets were not aligned at some point and so the software/hardware wasn't sure where the shutter position actually was?

**Comment by dave4roma** [comment] 2020-05-10 16:48
> I still think its to do with the magnets not correctly reporting that the shutter is "closed" or "open". Maybe you closed the shutter when the magnets were not aligned at some point and so the software/hardware wasn't sure where the shutter position actually was?

I’m sorry but I don’t think that’s it. The magnets line up fine when it opens or closes. I reinstalled the firmware and cycled power. It just bails out in the middle of a move. And the driver throws a com error 206 and it causes it to disconnect or error our thesky. I don’t see a magnet issue causing that.

**Comment by NameOfTheDragon** [comment] 2020-05-11 00:29
It is unlikely to be a problem with the magnets because:

1. Every time the shutter reaches the CLOSE position, it resynchronizes its position to zero.
2. The shutter will open a set distance unless the magnet is encountered first.

For the shutter to stop early, then these are the possibilities that I can imagine.

1. The shutter "range of travel" setting got corrupted so the "set distance" is now too short. You can check this by issuing the `@RRS` firmware command ("range read shutter"). It should respond 
> @RRS
> :RRS46000#

2. A false detection on the open/close sensor inputs. Reed switches are mechanical and it is possible for them to be activated by vibration or shock. To rule this out as a possibility, you could try disconnecting the sensors and relying only on the firmware's concept of the shutter range of travel. You may like to write a shorter travel distance into the firmware to avoid crashing into the physical end of travel. This can be achieved using `@RWS,40000` (40000 is the number of full steps to fully open the shutter, 46000 is the default value. Keep in mind that your shutter will never report "closed" with the sensor removed.

3. A voltage spike is crashing the Arduino and/or causing it to reboot. This will be difficult to diagnose and it's not something I see on the test bench using mains power. In the last firmware update, I added a "heartbeat" indicator in both the rotator and shutter. It might be useful to have a look and see if this is doing anything when you get the error. On the Arduino there is a series of LEDs. There's a red power LED and next to that is the green "heartbeat" LED. There are more LEDs that are associated with the USB/serial port and the XBee radio, all of which may be waggling on and off. The one I am interested in is the green LED right next to the red power LED, it should be flashing at 2Hz (on and off twice a second).

**Comment by dave4roma** [comment] 2020-05-11 01:33
> It is unlikely to be a problem with the magnets because:
> 
> 1. Every time the shutter reaches the CLOSE position, it resynchronizes its position to zero.
> 2. The shutter will open a set distance unless the magnet is encountered first.
> 
> For the shutter to stop early, then these are the possibilities that I can imagine.
> 
> 1. The shutter "range of travel" setting got corrupted so the "set distance" is now too short. You can check this by issuing the `@RRS` firmware command ("range read shutter"). It should respond
> 
> > `@RRS`
> > :RRS46000#
> 
> 1. A false detection on the open/close sensor inputs. Reed switches are mechanical and it is possible for them to be activated by vibration or shock. To rule this out as a possibility, you could try disconnecting the sensors and relying only on the firmware's concept of the shutter range of travel. You may like to write a shorter travel distance into the firmware to avoid crashing into the physical end of travel. This can be achieved using `@RWS,40000` (40000 is the number of full steps to fully open the shutter, 46000 is the default value. Keep in mind that your shutter will never report "closed" with the sensor removed.
> 2. A voltage spike or dip is crashing the Arduino and/or causing it to reboot. This will be difficult to diagnose and it's not something I see on the test bench using mains power. In the last firmware update, I added a "heartbeat" indicator in both the rotator and shutter. It might be useful to have a look and see if this is doing anything when you get the error. On the Arduino there is a series of LEDs. There's a red power LED and next to that is the green "heartbeat" LED. There are more LEDs that are associated with the USB/serial port and the XBee radio, all of which may be waggling on and off. The one I am interested in is the green LED right next to the red power LED, it should be flashing at 2Hz (on and off twice a second).
>>>
Well,  for what it’s worth I not sure I solved the problem but maybe.

I took off the cover and checked voltages all around with a voltmeter and all looked okay.

Then I moved off the charge terminals and unplugged the main power to the board.

I went around all the connector posts with a flat screwdriver and tightened down all the contacts. I felt a few that had some slack to them.  Also tightened down the ones for the motor board.

Put the cover back on and plugged her in.

So far I’ve been able to connect via TheSkyX and hold connection for a while. Also was able to issue open, abort, and close commands with the ‘last open’ and ‘last close successful’ messages when the shutter got to the magnets.

Have not seen another ‘error 206’ com error yet.

It’s only been one night of testing. But I think securing all the terminals and posts was helpful.

I’ve never done that since I got the motor kit so maybe after a year and weather cycles it just needed a tightening up.

I hope that fix holds.  Sorry to get your mind spun up on possible solutions. But if this doesn’t stay fixed I will check all the above.

**Comment by NameOfTheDragon** [comment] 2021-01-13 15:15
Resolved by user. It would be worth adding a page in the wiki about this.

**Comment by NameOfTheDragon** [comment] 2021-01-13 16:07
Resolved by customer - section added in the troubleshooting wiki page

**Closed by NameOfTheDragon** 2021-01-13 16:07 UTC

**Comment by markm75** [comment] 2021-01-13 16:22
Same issue i reported in #17 but maybe slightly different, what was the ultimate fix in this thread, tightening screws?  Did it ever require the power button toggle to get it going again (thats the issue i have with mine in #17), curious.
